
-- Drop table

-- DROP TABLE twiath."ESPN_PLAYERS";

CREATE TABLE twiath."ESPN_PLAYERS" (
	"ESPN_ID" int4 NOT NULL,
	"NFL_TEAM" varchar(3) NULL,
	"PLAYER_FIRST_NAME" varchar(50) NULL,
	"PLAYER_LAST_NAME" varchar(50) NULL,
	"PLAYER_FULL_NAME" varchar(50) NULL,
	"UNIFORM_NUMBER" usmallint NULL,
	"POSITION" varchar(2) NULL,
	"AGE" int4 NULL,
	"HEIGHT" varchar(10) NULL,
	"WEIGHT" int2 NULL,
	"YEARS_PRO" int2 NULL,
	"COLLEGE" varchar(255) NULL,
	"ESPN_LINK" varchar(255) NULL,
	CONSTRAINT espn_players_pkey PRIMARY KEY ("ESPN_ID")
);

-- Drop table

-- DROP TABLE twiath."LEAGUE";

CREATE TABLE twiath."LEAGUE" (
	"LEAGUEID" int4 NOT NULL,
	"LEAGUENAME" varchar(50) NOT NULL,
	CONSTRAINT "PK9" PRIMARY KEY ("LEAGUEID")
);

-- Drop table

-- DROP TABLE twiath."OWNER";

CREATE TABLE twiath."OWNER" (
	"OWNERID" varchar(50) NOT NULL,
	"FIRSTNAME" varchar(50) NULL,
	"LASTNAME" varchar(50) NULL,
	"OWNERNAME" varchar(50) NULL,
	CONSTRAINT "PK2" PRIMARY KEY ("OWNERID")
);

-- Drop table

-- DROP TABLE twiath."PLAYER";

CREATE TABLE twiath."PLAYER" (
	"PLAYERID" int4 NOT NULL,
	"POSITION" varchar(5) NOT NULL,
	"NFLTEAM" varchar(50) NOT NULL,
	"FIRSTNAME" varchar(50) NOT NULL,
	"LASTNAME" varchar(50) NOT NULL,
	CONSTRAINT "PK1" PRIMARY KEY ("PLAYERID")
);

-- Drop table

-- DROP TABLE twiath."SCORING";

CREATE TABLE twiath."SCORING" (
	"SCORINGID" int4 NOT NULL,
	"PASSINGYARDS" float8 NULL,
	"INTERCEPTIONSTHROWN" float8 NULL,
	"RUSHINGYARDS" float8 NULL,
	"TDPASS" float8 NULL,
	"TWPTPASSINGCONVERSION" float8 NULL,
	"TDRUSH" float8 NULL,
	"TWOPTRUSHINGCONVERSION" float8 NULL,
	"TDRECEPTION" float8 NULL,
	"RECEIVINGYARDS" float8 NULL,
	"TWOPTRECEIVINGCONVERSION" float8 NULL,
	"KICKOFFRETURNTD" float8 NULL,
	"PUNTRETURNTD" float8 NULL,
	"TOTALFUMBLES" float8 NULL,
	"FUMBLERECOVEREDTD" float8 NULL,
	"TOTALFUMBLESLOST" float8 NULL,
	"PATMADE" float8 NULL,
	"PATMISSED" float8 NULL,
	"FGMADE40_49" float8 NULL,
	"FGMISSED0_39" float8 NULL,
	"FGMADE0_39" float8 NULL,
	"FGMADE50" float8 NULL,
	"FGMISSED40_49" float8 NULL,
	"SACK" float8 NULL,
	"DEFFUMBLERETURNTD" float8 NULL,
	"DEFPUNTRETURNTD" float8 NULL,
	"BLOCKEDPUNTPATORFG" float8 NULL,
	"FUMBLESRECOVERED" float8 NULL,
	"SAFETY" float8 NULL,
	"INTERCEPTIONRETURNTD" float8 NULL,
	"DEFKICKOFFRETURNTD" float8 NULL,
	"BLOCKEDPUNTORFGRETURNFORTD" float8 NULL,
	"INTERCEPTION" float8 NULL,
	"FUMBLEFORCED" float8 NULL,
	"STUFFS" float8 NULL,
	"BASEPOINTS" float8 NULL,
	"ONEPTRETURN" float8 NULL,
	"TWOPTRETURN" float8 NULL,
	"POINTSALLOWED" float8 NULL,
	"YARDSALLOWED" float8 NULL,
	CONSTRAINT "PK11" PRIMARY KEY ("SCORINGID")
);

-- Drop table

-- DROP TABLE twiath."WEEK";

CREATE TABLE twiath."WEEK" (
	"WEEKID" int4 NOT NULL,
	"WEEK" int4 NOT NULL,
	"YEAR" int4 NOT NULL,
	CONSTRAINT "PK4" PRIMARY KEY ("WEEKID")
);

-- Drop table

-- DROP TABLE twiath."PERFORMANCE";

CREATE TABLE twiath."PERFORMANCE" (
	"PERFORMANCEID" int4 NOT NULL,
	"PASSINGYARDS" varchar(50) NULL,
	"INTERCEPTIONSTHROWN" varchar(50) NULL,
	"RUSHINGYARDS" varchar(50) NULL,
	"TDPASS" varchar(50) NULL,
	"TWPTPASSINGCONVERSION" varchar(50) NULL,
	"TDRUSH" varchar(50) NULL,
	"TWOPTRUSHINGCONVERSION" varchar(50) NULL,
	"TDRECEPTION" varchar(50) NULL,
	"RECEIVINGYARDS" varchar(50) NULL,
	"TWOPTRECEIVINGCONVERSION" varchar(50) NULL,
	"KICKOFFRETURNTD" bpchar(10) NULL,
	"PUNTRETURNTD" varchar(50) NULL,
	"TOTALFUMBLES" varchar(50) NULL,
	"FUMBLERECOVEREDTD" varchar(50) NULL,
	"TOTALFUMBLESLOST" varchar(50) NULL,
	"PATMADE" varchar(50) NULL,
	"PATMISSED" varchar(50) NULL,
	"FGMADE40_49" varchar(50) NULL,
	"FGMISSED0_39" varchar(50) NULL,
	"FGMADE0_39" varchar(50) NULL,
	"FGMADE50" varchar(50) NULL,
	"FGMISSED40_49" varchar(50) NULL,
	"SACK" varchar(50) NULL,
	"DEFFUMBLERETURNTD" varchar(50) NULL,
	"PUNTRETURNTD_1" varchar(50) NULL,
	"BLOCKEDPUNTPATORFG" varchar(50) NULL,
	"FUMBLESRECOVERED" varchar(50) NULL,
	"SAFETY" varchar(50) NULL,
	"INTERCEPTIONRETURNTD" varchar(50) NULL,
	"DEFKICKOFFRETURNTD" varchar(50) NULL,
	"BLOCKEDPUNTORFGRETURNFORTD" varchar(50) NULL,
	"INTERCEPTION" varchar(50) NULL,
	"FUMBLEFORCED" varchar(50) NULL,
	"STUFFS" varchar(50) NULL,
	"BASEPOINTS" varchar(50) NULL,
	"PTRETURN" varchar(50) NULL,
	"POINTSALLOWED" varchar(50) NULL,
	"YARDSALLOWED" varchar(50) NULL,
	"WEEKID" int4 NOT NULL,
	"PLAYERID" int4 NOT NULL,
	CONSTRAINT "PK10" PRIMARY KEY ("PERFORMANCEID"),
	CONSTRAINT "PERFORMANCE_PLAYERID_fkey" FOREIGN KEY ("PLAYERID") REFERENCES twiath."PLAYER"("PLAYERID") ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT "PERFORMANCE_WEEKID_fkey" FOREIGN KEY ("WEEKID") REFERENCES twiath."WEEK"("WEEKID") ON UPDATE CASCADE ON DELETE CASCADE
);

-- Drop table

-- DROP TABLE twiath."TEAM";

CREATE TABLE twiath."TEAM" (
	"TEAMID" int4 NOT NULL,
	"TEAMNAME" varchar(40) NOT NULL,
	"LEAGUEID" int4 NOT NULL,
	"OWNERID" varchar(50) NOT NULL,
	"OWNERNAME" varchar(50) NULL,
	CONSTRAINT "PK8" PRIMARY KEY ("TEAMID"),
	CONSTRAINT "TEAM_OWNERID_fkey" FOREIGN KEY ("OWNERID") REFERENCES twiath."OWNER"("OWNERID") ON UPDATE CASCADE ON DELETE CASCADE
);

-- Drop table

-- DROP TABLE twiath."MATCHUP";

CREATE TABLE twiath."MATCHUP" (
	"MATCHUPID" int4 NOT NULL,
	"AWAYTEAM" int4 NOT NULL,
	"WEEKID" int4 NOT NULL,
	"HOMETEAM" int4 NOT NULL,
	CONSTRAINT "PK6" PRIMARY KEY ("MATCHUPID"),
	CONSTRAINT "MATCHUP_AWAYTEAM_fkey" FOREIGN KEY ("AWAYTEAM") REFERENCES twiath."TEAM"("TEAMID") ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT "MATCHUP_HOMETEAM_fkey" FOREIGN KEY ("HOMETEAM") REFERENCES twiath."TEAM"("TEAMID") ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT "MATCHUP_WEEKID_fkey" FOREIGN KEY ("WEEKID") REFERENCES twiath."WEEK"("WEEKID") ON UPDATE CASCADE ON DELETE CASCADE
);

-- Drop table

-- DROP TABLE twiath."ROSTER";

CREATE TABLE twiath."ROSTER" (
	"PLAYERID" int4 NOT NULL,
	"TEAMID" int4 NOT NULL,
	"WEEKID" int4 NOT NULL,
	starter_bench varchar(7) NULL,
	CONSTRAINT "PK5" PRIMARY KEY ("PLAYERID", "TEAMID", "WEEKID"),
	CONSTRAINT "ROSTER_PLAYERID_fkey" FOREIGN KEY ("PLAYERID") REFERENCES twiath."PLAYER"("PLAYERID") ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT "ROSTER_TEAMID_fkey" FOREIGN KEY ("TEAMID") REFERENCES twiath."TEAM"("TEAMID") ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT "ROSTER_WEEKID_fkey" FOREIGN KEY ("WEEKID") REFERENCES twiath."WEEK"("WEEKID") ON UPDATE CASCADE ON DELETE CASCADE
);
